name: Deploy via SFTP (STRATO)

on:
    push:
        branches: ["main"]
        paths:
            - ".config/private.example.php"
            - ".github/workflows/deploy.yml"
            - "accommodation/**"
            - "beauli/**"
            - "contact/**"
            - "css/**"
            - "directors/**"
            - "doctors/**"
            # "downloads/**" -> siehe Worflow media-deploy.yml für Medien
            - "error/**"
            # "images/**" -> siehe Worflow media-deploy.yml für Medien
            - "include/**"
            - "js/**"
            - "legal-notices/**"
            - "location/**"
            - "partner/**"
            - "privacy-policy/**"
            - "program/**"
            - "register/**"
            - "science/**"
            - "index.php"
            - "README.md"
            - "robots.txt"
            - "site.webmanifest"
            - "sitemap.xml"
            - "version.txt"

    workflow_dispatch: {}

concurrency:
    group: "deploy-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: SFTP Deploy (only changed areas)
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  server: ${{ secrets.FTP_SERVER }} # ssh.strato.de
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: 22
                  sftp_only: true
                  local_path: "./index.php ./robots.txt ./site.webmanifest ./sitemap.xml ./version.txt ./accommodation/ ./beauli/ ./contact/ ./css/ ./directors/ ./doctors/ ./error/ ./include/ ./js/ ./legal-notices/ ./location/ ./partner/ ./privacy-policy/ ./program/ ./register/ ./science/"
                  remote_path: "/" # ggf. /httpdocs/ falls dein Webroot dort liegt
                  sftpArgs: "-o StrictHostKeyChecking=no"
